### ISSUE TITLE
Compiling issues with gcc10 (Type mismatch between actual argument)

### ISSUE THREAD

**Issue by AliE89** [sfilippone/psblas3#18]
Ciao Salvatore,

I am trying to compile psblas and amg4psblas to give them a try in my CFD code. 

I am getting the following issue while compiling with gcc-10.2.0  and openmpi-4.1.0 (screenshot attached):

![image](https://user-images.githubusercontent.com/49912570/169243577-2208e4d3-404d-4663-a894-76c4b41a804f.png)

What do you think the issue might be? 

Cheers

**Comment by AliE89** [comment]
So It looks like that this is something starting to appear from gcc-10 and a work aroud is to add "-fallow-argument-mismatch" to the FFLAGS.  However, I am ahppy if you want to check on your side :)

**Comment by sfilippone** [comment]
Yes, that is correct, -fallow-arguments-mismatch solves this and other issues down the line.
I am actually designing and working on version 4, which is going to have a slightly different internal setup, so that that compiler flag will no longer be needed.

As for PSBLAS3, if you download the development branch, the fix was  already included  in the configure script; pls let me know if it works for you

Salvatore

**Comment by sfilippone** [comment]
> Yes, that is correct, -fallow-arguments-mismatch solves this and other issues down the line. I am actually designing and working on version 4, which is going to have a slightly different internal setup, so that that compiler flag will no longer be needed.
> 
> As for PSBLAS3, if you download the development branch, the fix was already included in the configure script; pls let me know if it works for you
> 
> Salvatore

I plan to publish shortly version 3.8, which will contain some changes/enhancements in the matrix build procedure, so this fix will be included in the next release; it would be appreciated if you could verify it works.
Thanks

**Comment by sfilippone** [comment]
Version 3.8.0 published, should be fixed by now.

**Comment by sfilippone** [comment]
Yes, that is correct, -fallow-arguments-mismatch solves this and other
issues down the line.
I am actually designing and working on version 4, which is going to have a
slightly different internal setup, so that that compiler flag will no
longer be needed.

As for PSBLAS3, if you download the development branch, it should be
already fixed in the configure script; pls let me know if it works for you

Salvatore
